# Generated by Django 4.2.20 on 2025-04-26 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('university', models.CharField(blank=True, max_length=255)),
                ('pages', models.IntegerField()),
                ('language', models.CharField(choices=[('uz', 'O‘zbek'), ('ru', 'Rus'), ('en', 'Ingliz')], max_length=20)),
                ('file', models.FileField(blank=True, upload_to='courseworks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.field')),
            ],
        ),
    ]
